[package]
name = "daoyi-rust-gateway"
version = "0.1.0"
edition = "2024"

[dependencies]
salvo = { version = "0.78.0", features = ["proxy"] }
tokio = { version = "1.44.2", features = ["macros"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"